# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apple Notes Exporter' do
  pod 'SSZipArchive'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apple Notes Exporter

  target 'Apple Notes ExporterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Apple Notes ExporterUITests' do
    # Pods for testing
  end

end
